### ISSUE TITLE
Home Page Problems

### ISSUE THREAD

**Issue by ihsanhere** [quarkuslab/honey-museum#7]
### Multiple scrollbars Issue
![Image](https://github.com/user-attachments/assets/1df1b96a-b49c-4c0c-8931-5a9435d985f7)
- make only one scrollbar
- issue with overflow-x on main element

### Unnecessary Text
![Image](https://github.com/user-attachments/assets/b9146a0d-716f-4a94-b2f9-7a26cfb39f2d)

### Instagram image Improvements
1. center the image
2. reduce the size of image
3. open instagram in new tab when clicked

### Products alignment and size improvements
- use grid layout to align the product components
-  use fixed spacing between products (using gap)

**Comment by adheeb2** [comment]
how much smaller should the size of instagram page be, just send an outline for better understanding
